spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:catcher}?createDatabaseIfNotExist=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true
    username: ${DB_USER:test}
    password: ${DB_PASS:test}
  jpa: # disable stacktrace on system start from hibernate (checking supported features)
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        clientId: catcher
        clientSecret: catcher_secret
        scope: read,write
        autoApproveScopes: '.*'
catcher:
  base:
    local_dir: ${LOCAL_DIR:./}
    jwt:
      private: ${JWT_PRIV:catcher_priv}
  system:
    native_executable: python
    pip_executable: pip
  executor:
    local:
      pool:
        max_size: ${MAX_POOL_SIZE:2}
        core_size: ${CORE_POOL_SIZE:1}
server:
  port: ${SERVER_PORT:8080}
  version: ${version}